### PR TITLE
Enable compatibility with PHP 8

### PR DESCRIPTION
**Pull request by rthiago**
This PR makes it possible to work with PHP 8. Also I moved phpunit requirement to dev.

### CODE REVIEW

**Comment by timhj** [comment]
@vicchi - HI Gary, can you accept this pull request and update the package with it? There are no code changes required for it to work with PHP 8 so should be a quick one to do. Appreciate if you can find the time!

**Comment by vicchi** [comment]
@rthiago @timhj Yikes ... how the heck did I miss this PR? Will remedy this today

**Comment by vicchi** [comment]
Merged and resolved in commit b4122fad6f94e6e27f477f56a6d931e8bbfab59d; will merge to `master` shortly and tag as `v1.0.1`.

**Comment by timhj** [comment]
Amazing, thank you. Composer is happy again.

**Pull request closed without merging**
